# Generated by Django 4.1.3 on 2022-11-23 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problem',
            fields=[
                ('problem_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('chapter', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('contents', models.CharField(max_length=500)),
                ('restrict', models.CharField(max_length=500)),
                ('testcase1', models.CharField(max_length=200)),
                ('testcase2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user_log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('auto_saved', models.CharField(max_length=200)),
                ('save1', models.CharField(max_length=200)),
                ('save2', models.CharField(max_length=200)),
                ('save3', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=1)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.problem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user')),
            ],
        ),
    ]
