# Generated by Django 4.1.3 on 2022-11-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_log',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='problem',
            name='contents',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='restrict',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='auto_saved',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='save1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='save2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='save3',
            field=models.TextField(),
        ),
    ]
