# Generated by Django 4.1.3 on 2022-11-24 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_user_log_user_id_alter_problem_contents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_log',
            name='log_id',
        ),
        migrations.AlterField(
            model_name='user_log',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='server.problem'),
        ),
    ]
