# Generated by Django 4.1.3 on 2022-11-24 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_user_log_log_id_alter_user_log_problem_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='problem_id',
            new_name='id',
        ),
    ]
