# Generated by Django 4.1.3 on 2022-11-24 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_problem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_log',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ProblemInfo', serialize=False, to='server.problem'),
        ),
    ]
