# Generated by Django 4.1.3 on 2022-11-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_problem_skeleton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='testcase1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='testcase2',
            field=models.TextField(),
        ),
    ]
