# Generated by Django 4.1.3 on 2022-12-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_alter_problem_testcase1_alter_problem_testcase2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_log',
            name='auto_saved',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='save1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='save2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='save3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='status',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
