# Generated by Django 4.1.3 on 2022-12-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_alter_user_log_auto_saved_alter_user_log_save1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_log',
            name='auto_saved',
            field=models.TextField(default='A'),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='save1',
            field=models.TextField(default='1'),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='save2',
            field=models.TextField(default='2'),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='save3',
            field=models.TextField(default='3'),
        ),
    ]
